export const couriers = [
  { name: "anteraja", logo: "/courier/anteraja.svg" },
  { name: "dse", logo: "/courier/dse.svg" },
  { name: "pos", logo: "/courier/pos.svg" },
  { name: "lion", logo: "/courier/lion.svg" },
  { name: "ninja", logo: "/courier/ninja.svg" },
  { name: "ide", logo: "/courier/ide.svg" },
  { name: "sicepat", logo: "/courier/sicepat.svg" },
  { name: "sap", logo: "/courier/sap.svg" },
  { name: "ncs", logo: "/courier/ncs.svg" },
  { name: "rex", logo: "/courier/rex.svg" },
  { name: "jtl", logo: "/courier/jtl.svg" },
  { name: "sentral", logo: "/courier/sentral.svg" },
  { name: "jne", logo: "/courier/jne.svg" },
  { name: "tiki", logo: "/courier/tiki.svg" },
  { name: "rpx", logo: "/courier/rpx.svg" },
  { name: "pandu", logo: "/courier/pandu.svg" },
  { name: "wahana", logo: "/courier/wahana.svg" },
  { name: "jnt", logo: "/courier/jnt.svg" },
  { name: "slis", logo: "/courier/slis.svg" },
  { name: "expedito", logo: "/courier/expedito.svg" },
  { name: "ray", logo: "/courier/ray.svg" },
  { name: "first", logo: "/courier/first.svg" },
  { name: "star", logo: "/courier/star.svg" },
];

export const dataDummy = [
  {
    name: "ID Express",
    code: "ide",
    service: "STD",
    description: "Std",
    cost: 73100,
    etd: "0-0 day",
  },
  {
    name: "J&T Express",
    code: "jnt",
    service: "EZ",
    description: "Reguler",
    cost: 55000,
    etd: "",
  },
  {
    name: "Jalur Nugraha Ekakurir (JNE)",
    code: "jne",
    service: "JTR",
    description: "JNE Trucking",
    cost: 180000,
    etd: "10 day",
  },
  {
    name: "Jalur Nugraha Ekakurir (JNE)",
    code: "jne",
    service: "OKE",
    description: "Ongkos Kirim Ekonomis",
    cost: 60000,
    etd: "6 day",
  },
  {
    name: "Jalur Nugraha Ekakurir (JNE)",
    code: "jne",
    service: "REG",
    description: "Layanan Reguler",
    cost: 70000,
    etd: "5 day",
  },
  {
    name: "Ninja Xpress",
    code: "ninja",
    service: "STANDARD",
    description: "Standard Service",
    cost: 60600,
    etd: "",
  },
  {
    name: "POS Indonesia (POS)",
    code: "pos",
    service: "Pos Reguler",
    description: "240",
    cost: 59500,
    etd: "6 day",
  },
  {
    name: "POS Indonesia (POS)",
    code: "pos",
    service: "PKH Marketplace",
    description: "Ec3",
    cost: 52000,
    etd: "6 day",
  },
  {
    name: "Royal Express Indonesia (REX)",
    code: "rex",
    service: "REG",
    description: "Regular",
    cost: 73000,
    etd: "5-5 day",
  },
  {
    name: "Royal Express Indonesia (REX)",
    code: "rex",
    service: "EXP",
    description: "Express",
    cost: 76000,
    etd: "5-5 day",
  },
  {
    name: "Satria Antaran Prima",
    code: "sap",
    service: "DRGREG",
    description: "Cargo",
    cost: 255000,
    etd: "7-10 day",
  },
  {
    name: "Satria Antaran Prima",
    code: "sap",
    service: "UDRREG",
    description: "Reguler",
    cost: 64000,
    etd: "4-7 day",
  },
  {
    name: "SiCepat Express",
    code: "sicepat",
    service: "BBM",
    description: "Berani Bayar Murah",
    cost: 67500,
    etd: "7-10 day",
  },
  {
    name: "SiCepat Express",
    code: "sicepat",
    service: "GOKIL",
    description: "Cargo Per Kg (Minimal 10kg)",
    cost: 310000,
    etd: "7-13 day",
  },
  {
    name: "SiCepat Express",
    code: "sicepat",
    service: "REG",
    description: "Reguler",
    cost: 57000,
    etd: "5-7 day",
  },
];
